@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2

    Class "CsvUtil (Model.util)" as CsvUtil MODEL_COLOR_T1
    Class "AddressBook JSON\nUserPrefs JSON\nCommandHistory JSON" as Persisted STORAGE_COLOR_T1
    Class "CommandHistory (UI)" as UICommandHistory UI_COLOR_T1
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#green]> Logic
UI -right[#green]-> Model
Logic -[#blue]-> Storage
Logic -down[#blue]-> Model
Main -[#grey]-> UI
Main -[#grey]-> Logic
Main -[#grey]-> Storage
Main -up[#grey]-> Model
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> Model
Storage .right[STORAGE_COLOR].>File

Storage -[dashed,STORAGE_COLOR]-> Persisted : saves/loads

Logic -[dashed,#000000]-> CsvUtil : import/export CSV
Model -[dashed,#000000]-> CsvUtil

UI -[dashed,#000000]-> UICommandHistory : navigate history

User ..> UI
@enduml
