title: "MeshCRM"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2526S1-CS2103T-W12-3a/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
